<?php
/*GLOBAL SETTINGS PAGE.

ONLY USE BOOLEAN VALUES false AND true AS SPECIFIED.
DON'T CHANGE ANYTHING ELSE.*/

				define('globAC',
       /*RUN CONFIGURE.PHP AUTOMATICALLY*/ true  /*YOU MUST MANUALLY RUN CONFIGURE.PHP IF false*/
				);define('globOff',
/*TRY TO GET DATA ONLY OFF LOCAL SERVER:*/ false /*IF REMOTE SERVER, false WORKS BETTER*/
				);?>